dist: trusty
language: node_js
node_js:
  - "8.9.1"
addons:
  chrome: beta
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &